# Generated by Django 4.2.7 on 2023-11-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReplaceableParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaceable_parts', to='inventory_management.inventoryitem')),
                ('replaceable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_parts', to='inventory_management.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.uploadversion'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_upload_version_constraint'),
        ),
    ]
