# Generated by Django 4.2.7 on 2023-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='not_matched_replaceable_parts',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
